### ISSUE TITLE
Slack invite link missing

### ISSUE THREAD

**Issue by hobytodges** [carpentries/carpentries.org#316]
@OscarSiba Although we link to the `#general` channel in a few locations, the invitation link for people to join our Slack workspace is not included in the site anymore. Was this intentional? Those channel links will only work for people who already have an account and are logged in.

**Comment by OscarSiba** [comment]
Hi Toby. I'm not sure I fully understand what you mean... Are the links [here](https://carpentries.org/about-us/contact/) and [here](https://carpentries.org/community/get-involved/) not the correct link we should be using? If not, what link do you recommend for people wanting to join our Slack?

**Comment by tobyhodges** [comment]
The links on those pages are to the general channel, but that is only accessible to people who already have an account on the workspace. Anyone without an account will be told they can only create an account using an email address with one of our domains (see screenshot below). To get around the pain of needing to create accounts or share an invite link individually with people who want to join the workspace, we have an application setup that creates accounts for people on-demand. The link to this app is https://slack-invite.carpentries.org/ I think we should provide that link somewhere on the website, so that newcomers can create an account.

<img width="677" alt="Screenshot 2024-12-03 at 16 20 17" src="https://github.com/user-attachments/assets/606482ff-79aa-4970-a7df-745260c3b6b1">

**Comment by tobyhodges** [comment]
Sorry I just noticed I opened this with my alter-ego account! 😂 I was logged in for a CLDT event yesterday and lost track of which browser window I was working in.

**Comment by maneesha** [comment]
This depends on what we mean by "join" Slack.  We may want to have existing users enter the Slack workspace (https://carpentries.slack.com/),  or we may want to have new users sign up for the Slack workspace (https://slack-invite.carpentries.org/).  

The first link does not offer a way for new users to sign up.
The second link allows new users to sign up and has another link for existing users to follow.  So while the second link requires an extra click for existing users, that's probably the preferable option.

**Comment by OscarSiba** [comment]
LOL. Thanks @tobyhodges. Ok, now I understand what you mean. 

@maneesha please edit the contact page and the [get involved page](https://carpentries.org/community/get-involved/) as follows:

- [ ] On the contact page where it is say "On Slack" please list the following:
       [Join The Carpentries Slack Workspace](https://slack-invite.carpentries.org/) 
       [Log into The Carpentries General Slack Channel](https://carpentries.slack.com/?redir=%2Farchives%2FC03LE48AY%3Fname%3DC03LE48AY)
 
- [ ] Do same as the first two listed items on the Get involved page. 

Let me know @tobyhodges if you don't think this sufficiently addresses the problem.
